name = "livetrip-planner"
compatibility_date = "2025-06-12"

pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "live-trip-planner-db"
database_id = "e55520b5-bfcf-4a76-a2cc-6b4dc9e9b7c9"